language: python

notifications:
  email: false

  webhooks:
    urls:
      - https://webhooks.gitter.im/e/06cf2c44aa8e55ab06c8
    on_success: always
    on_failure: always
    on_start: false

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - pypy

before install:

 - sudo apt-get update
 - sudo apt-get install wget build-essential
 - sudo apt-get install python3-setuptools python-setuptools
 - sudo apt-get install python3-dev python-dev

install:

 - sudo apt-get install python3-nose python-nose
 - sudo apt-get install pep8
 - pip install coveralls

script:

 - ./test_travis.sh

after_success:
  coveralls
