language: python

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/06cf2c44aa8e55ab06c8
    on_success: always
    on_failure: always
    on_start: false

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - pypy

before install:

 - sudo apt-get update
 - sudo apt-get install wget build-essential 
 - sudo apt-get install python3-setuptools python-setuptools 
 - sudo apt-get install python3-dev python-dev
 
install:

 - sudo apt-get install libqt4-dev python-qt4 pyqt4-dev-tools qt4-designer
 - sudo apt-get install python3-nose python-nose 
 - sudo apt-get install pep8
 
 # install SIP
 
 - wget http://jaist.dl.sourceforge.net/project/pyqt/sip/sip-4.15.5/sip-4.15.5.tar.gz
 - tar zxvf sip-4.15.5.tar.gz
 - cd sip-4.15.5
 - python configure.py
 - make --silent
 - sudo make install --silent

 # For python3
 
 - python3 configure.py  
 - make --silent
 - sudo make install --silent

 - cd ..

# install PyQt4

 - wget http://jaist.dl.sourceforge.net/project/pyqt/PyQt4/PyQt-4.10.4/PyQt-x11-gpl-4.10.4.tar.gz
 - tar zxvf PyQt-x11-gpl-4.10.4.tar.gz
 - cd PyQt-x11-gpl-4.10.4/
 - echo 'yes' | python configure.py
 - make --silent
 - sudo make install --silent
 
# For python3
 
 - echo 'yes' | python3 configure.py  
 - make --silent
 - sudo make install --silent
 
# clean up sources so that they dont affect the pep8 test

 - cd ..
 - rm -R PyQt-x11-gpl-4.10.4/
 - rm -R sip-4.15.5
 
# try importing the newly installed packages
 
 - python -c 'import sip'
 - python -c 'import PyQt4'
 - python -c 'import PyQt4.QtCore'
  
script:

 - pep8 --ignore=E501 ./
 - nosetests
 - nosetests3
 - cd BinPy/tests/
 - nosetests -v gates_tests.py
 - nosetests -v combinational_tests.py
 - nosetests -v operations_tests.py
 - nosetests -v sequential_tests.py
 - nosetests -v counters_tests.py
 - nosetests -v series_4000_tests.py
 - nosetests -v series_7400_tests.py
 - nosetests -v source_tests.py
 - nosetests -v sequential_ic_tests.py
 - nosetests -v registers_tests.py
 - nosetests -v tree_tests.py
 - nosetests -v print_tests.py
 - nosetests -v expr_tests.py
 - nosetests -v analog_devices_tests.py
 - nosetests -v analog_source_tests.py
 - nosetests3 -v gates_tests.py
 - nosetests3 -v combinational_tests.py
 - nosetests3 -v operations_tests.py
 - nosetests3 -v sequential_tests.py
 - nosetests3 -v counters_tests.py
 - nosetests3 -v series_4000_tests.py
 - nosetests3 -v series_7400_tests.py
 - nosetests3 -v source_tests.py
 - nosetests3 -v sequential_ic_tests.py
 - nosetests3 -v registers_tests.py
 - nosetests3 -v tree_tests.py
 - nosetests3 -v print_tests.py
 - nosetests3 -v expr_tests.py
 - nosetests3 -v analog_devices_tests.py
 - nosetests3 -v analog_source_tests.py
