sudo : false

language: python

notifications:
  email: false

  webhooks:
    urls:
      - https://webhooks.gitter.im/e/06cf2c44aa8e55ab06c8
    on_success: always
    on_failure: always
    on_start: false

addons:
  apt:
    packages:

cache:
  directories:
    - $HOME/.cache/pip

python:
  - 2.7
  - 3.2
  - 3.3
  - 3.4

install:

 - pip install --upgrade pip
 - pip install pep8
 - pip install coverage
 - pip install python-coveralls
 - pip install networkx
 - pip install bitstring

script:

 - sudo chmod 777 test_travis.sh
 - ./test_travis.sh

after_success:
  coveralls

notifications:
  irc: "chat.freenode.net#binpy-soc"
